#!/bin/bash
echo "Starting plotting analysis"

echo "Plotting nosZI charts"
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_rare_curve.R --input /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/nosZI_alpha_rare.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index richness --input /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/nosZI_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index chao1 --input /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/nosZI_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index shannon --input /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/nosZI_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index simpson --input /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/nosZI_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index invsimpson --input /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/nosZI_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index ACE --input /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/nosZI_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZI/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/beta_pcoa.R --input /project/wujp/zbs/wyy_0308/merge/nosZI/beta/bray_curtis.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZI/beta/nosZI_bray_curtis.pcoa.pdf --width 89 --height 59 --label FALSE
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_phylum_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_phylum_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZI/taxonomy/nosZI_phylum_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_class_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_class_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZI/taxonomy/nosZI_class_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_order_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_order_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZI/taxonomy/nosZI_order_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_family_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_family_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZI/taxonomy/nosZI_family_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_genus_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_genus_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZI/taxonomy/nosZI_genus_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_species_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_species_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZI/taxonomy/nosZI_species_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_rpkm.txt ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/gene_rpkm_boxplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_merged_rpkm.txt --group metadata.txt --output /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_rpkm.pdf --width 160 --height 110
fi
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/network_plot.R --input /project/wujp/zbs/wyy_0308/merge/nosZI/nosZI_otutab.txt --group metadata.txt --output /project/wujp/zbs/wyy_0308/merge/nosZI/network --width 16 --height 11

echo "Plotting nosZII charts"
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_rare_curve.R --input /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/nosZII_alpha_rare.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index richness --input /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/nosZII_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index chao1 --input /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/nosZII_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index shannon --input /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/nosZII_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index simpson --input /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/nosZII_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index invsimpson --input /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/nosZII_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index ACE --input /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/nosZII_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/beta_pcoa.R --input /project/wujp/zbs/wyy_0308/merge/nosZII/beta/bray_curtis.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZII/beta/nosZII_bray_curtis.pcoa.pdf --width 89 --height 59 --label FALSE
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_phylum_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_phylum_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZII/taxonomy/nosZII_phylum_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_class_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_class_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZII/taxonomy/nosZII_class_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_order_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_order_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZII/taxonomy/nosZII_order_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_family_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_family_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZII/taxonomy/nosZII_family_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_genus_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_genus_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZII/taxonomy/nosZII_genus_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_species_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_species_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZII/taxonomy/nosZII_species_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_rpkm.txt ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/gene_rpkm_boxplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_merged_rpkm.txt --group metadata.txt --output /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_rpkm.pdf --width 160 --height 110
fi
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/network_plot.R --input /project/wujp/zbs/wyy_0308/merge/nosZII/nosZII_otutab.txt --group metadata.txt --output /project/wujp/zbs/wyy_0308/merge/nosZII/network --width 16 --height 11

echo "Plotting nosZIII charts"
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_rare_curve.R --input /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/nosZIII_alpha_rare.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index richness --input /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/nosZIII_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index chao1 --input /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/nosZIII_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index shannon --input /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/nosZIII_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index simpson --input /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/nosZIII_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index invsimpson --input /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/nosZIII_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/alpha_boxplot.R --alpha_index ACE --input /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/nosZIII_alpha_div.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZIII/alpha/ --width 89 --height 59
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/beta_pcoa.R --input /project/wujp/zbs/wyy_0308/merge/nosZIII/beta/bray_curtis.txt --design metadata.txt --group Group --output /project/wujp/zbs/wyy_0308/merge/nosZIII/beta/nosZIII_bray_curtis.pcoa.pdf --width 89 --height 59 --label FALSE
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_phylum_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_phylum_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZIII/taxonomy/nosZIII_phylum_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_class_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_class_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZIII/taxonomy/nosZIII_class_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_order_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_order_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZIII/taxonomy/nosZIII_order_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_family_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_family_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZIII/taxonomy/nosZIII_family_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_genus_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_genus_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZIII/taxonomy/nosZIII_genus_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_species_rpkm.csv ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/tax_stackplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_species_rpkm.csv --design metadata.txt --group Group --color Paired --legend 9 --output /project/wujp/zbs/wyy_0308/merge/nosZIII/taxonomy/nosZIII_species_rpkm --width 89 --height 95
fi
if [ -f /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_rpkm.txt ]; then
  /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/gene_rpkm_boxplot.R --input /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_merged_rpkm.txt --group metadata.txt --output /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_rpkm.pdf --width 160 --height 110
fi
/project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/software/Rscript /project/wujp/zbs/nosZ/ninth_paper_20260307/pipeline/final_pipeline/sub/network_plot.R --input /project/wujp/zbs/wyy_0308/merge/nosZIII/nosZIII_otutab.txt --group metadata.txt --output /project/wujp/zbs/wyy_0308/merge/nosZIII/network --width 16 --height 11

echo "Plotting analysis completed"
